import type { ApiClient, ClarifyStreamResult } from '../api/client'
import { isTerminalConflict } from '../api/client'
import type { ClarifyMessage, ClarifyResponse, SubmissionSessionResponse } from '../types'

const POLL_INTERVAL_MS = 2000
// Give up polling after this long with no assistant reply so the card never spins
// forever (e.g. a backend job that silently died). This is the queued path — the
// answer is being generated by a job, not streamed — so it needs room for queue wait
// plus generation. The 12s deadline on the streaming request is a different budget:
// there, silence means the stream itself is stuck.
const POLL_TIMEOUT_MS = 45000
// How long a clarification stream may stay silent before it becomes retryable.
// Measured between tokens, not from the start, so a long answer is not cut off.
const CLARIFY_SILENCE_TIMEOUT_MS = 12000

// The card's lifecycle as one explicit state. These used to be six interacting
// booleans (done / sending / finalSubmissionStarted / finalizing /
// unrecoverable / submissionFailed) whose combinations encoded the states
// below; every guard had to reason about which combinations were possible.
// `destroyed` stays a separate flag on purpose: destruction can cut in from
// any state, and every post-await continuation checks it uniformly rather
// than folding it into each transition.
export type ClarifyState =
  // Waiting for the submission upload (initial mount or after a retry); the
  // input stays closed because there is no session to deliver a reply to.
  | 'adopting-session'
  // The feedback itself never reached the server; only a full re-submission
  // helps, offered by the failure footer.
  | 'submission-failed'
  // The conversation is live: an assistant turn is running or the reporter
  // may type. No terminal outcome yet and no reporter answer in flight.
  | 'conversing'
  // The reporter's answer is in flight; once the exchange settles the card
  // finalizes without asking for a second click.
  | 'answering'
  // A failed clarification is being retried (retryClarification in flight).
  | 'retrying'
  // Clarification failed for good; the footer offers fallback submission and
  // a retry.
  | 'clarify-failed'
  // The exchange settled: waiting on the Send feedback click, or a finalize
  // attempt failed transiently and the footer offers finalize-retry.
  | 'settled'
  // onFinalize is in flight.
  | 'finalizing'
  // The server will never accept this session again (terminal 409).
  | 'unrecoverable'

// Every edge the drivers below actually take. `conversing` is also the
// construction default, which is why it may move to `adopting-session` (the
// pending-upload mount). Skip fires finalize from any live state, so every
// non-terminal state except submission-failed (skip there is a plain cancel —
// nothing on the server to finalize) has an edge to `finalizing`.
const LEGAL_TRANSITIONS: Record<ClarifyState, readonly ClarifyState[]> = {
  'adopting-session': ['conversing', 'submission-failed', 'finalizing'],
  'submission-failed': ['adopting-session'],
  'conversing': ['adopting-session', 'answering', 'settled', 'clarify-failed', 'finalizing'],
  'answering': ['conversing', 'settled', 'clarify-failed', 'finalizing'],
  'retrying': ['conversing', 'settled', 'clarify-failed', 'finalizing'],
  'clarify-failed': ['retrying', 'finalizing'],
  'settled': ['finalizing', 'unrecoverable'],
  'finalizing': ['settled'],
  'unrecoverable': [],
}

/**
 * Everything the session asks of the card. The card owns the DOM (footers,
 * bubbles, composer, dismissal); the session only reports which surface a
 * decision calls for, mirroring how SubmissionLifecycleHost keeps "which UI is
 * on screen" decided in one place. Footer render methods bind their buttons
 * back to the session's public drivers.
 */
export interface ClarifySessionHost {
  showThinking(): void
  removeThinking(): void
  renderConversation(messages: ClarifyMessage[], done: boolean): void
  appendStreamDelta(text: string): void
  endStreamingBubble(): void
  setInputDisabled(disabled: boolean): void
  /** Re-open the composer, re-mounting the conversation controls if a failure footer replaced them. */
  enableInput(): void
  clearError(): void
  renderSubmissionFailureFooter(): void
  renderClarifyFailureFooter(): void
  renderFinalizeButton(): void
  renderFinalizeRetryFooter(): void
  renderUnrecoverableFooter(): void
  showConversationControls(): void
  /** The answer left the composer: close it, echo the user bubble, clear the field. */
  onAnswerTurnStarted(text: string): void
  /** Saving the answer failed: restore the transcript and hand the text back editable. */
  onAnswerTurnFailed(messages: ClarifyMessage[], text: string): void
  /** A clarify retry is starting: re-mount a closed composer over the last transcript. */
  onRetryStarted(messages: ClarifyMessage[]): void
  /** Finalize is on the wire: busy-state everything except the header X. */
  onFinalizeStarted(): void
  /** Remove the card from screen (the card's destroy, which also disposes this session). */
  dismiss(): void
}

export interface ClarifySessionOptions {
  // Either the session is already known, or it is still being created — the
  // card mounts immediately either way and shows its thinking bubble while
  // pendingSession settles.
  submissionSessionId?: string
  submissionToken?: string
  pendingSession?: Promise<SubmissionSessionResponse | null>
  onRetrySubmission?: () => Promise<SubmissionSessionResponse | null>
  apiClient: ApiClient
  onFinalize: () => Promise<void> | void
  onSkip?: () => void
  onCancel?: () => void
}

/**
 * The clarify conversation's state machine and network drivers, extracted from
 * the DOM card so turn sequencing, the stream-vs-poll fallback, retry
 * decisions, and finalize triggering live with the state they read. No DOM
 * access: every visible consequence goes through ClarifySessionHost.
 */
export class ClarifySession {
  private submissionSessionId: string
  private submissionToken: string
  private apiClient: ApiClient
  private onFinalize: () => Promise<void> | void
  private onSkip?: () => void
  private onCancel?: () => void
  private pendingSession?: Promise<SubmissionSessionResponse | null>
  private onRetrySubmission?: () => Promise<SubmissionSessionResponse | null>

  private state: ClarifyState = 'conversing'
  private destroyed = false
  private lastMessages: ClarifyMessage[] = []
  private pollTimer: ReturnType<typeof setInterval> | null = null
  private pollDeadline = 0
  // The in-flight clarification stream, so closing the card can hang up on it
  // rather than leaving the connection reading into a card that is gone.
  private streamAbort: AbortController | null = null

  constructor(opts: ClarifySessionOptions, private host: ClarifySessionHost) {
    this.submissionSessionId = opts.submissionSessionId ?? ''
    this.submissionToken = opts.submissionToken ?? ''
    this.apiClient = opts.apiClient
    this.onFinalize = opts.onFinalize
    this.onSkip = opts.onSkip
    this.onCancel = opts.onCancel
    this.pendingSession = opts.pendingSession
    this.onRetrySubmission = opts.onRetrySubmission
  }

  // The single transition point. Every state change routes through here so a
  // breakpoint or log line can observe the whole machine — and so an edge the
  // table above does not list fails loudly instead of silently corrupting a
  // guard's reasoning.
  private setState(next: ClarifyState): void {
    if (!LEGAL_TRANSITIONS[this.state].includes(next)) {
      throw new Error(`Illegal clarify transition: ${this.state} -> ${next}`)
    }
    this.state = next
  }

  // The exchange reached a terminal outcome; no further turn may restart it.
  // This is what the old `done` flag guarded.
  private hasSettled(): boolean {
    return this.state === 'clarify-failed' || this.state === 'settled'
      || this.state === 'finalizing' || this.state === 'unrecoverable'
  }

  // A reporter-driven request is running; new sends and retries must wait.
  // This is what the old `sending` flag guarded.
  private isRequestInFlight(): boolean {
    return this.state === 'answering' || this.state === 'retrying'
  }

  // Guard for late initial-turn continuations. Every post-await path checks
  // `destroyed`; the initial-turn drivers additionally bail once finalization
  // has started (Skip & send fires finalize just before destroy), so a late
  // turn cannot repaint footers or arm polling under a finalize already
  // running for this card.
  private abandoned(): boolean {
    return this.destroyed || this.state === 'finalizing'
  }

  // Guard for every other continuation (session adoption, the answer turn,
  // polling, retries, finalize): destruction alone. Deliberately narrower than
  // abandoned() — these drivers are the ones that *produce* `finalizing`
  // (an answered exchange finalizes itself), so folding that state into their
  // guard would cut them off mid-hand-off. The asymmetry is the point; do not
  // normalize the two.
  private gone(): boolean {
    return this.destroyed
  }

  async start(): Promise<void> {
    this.host.showThinking()
    if (this.pendingSession) {
      // No session id yet, so an eager reply could not be delivered anywhere —
      // keep the input closed until the assistant's question arrives.
      this.setState('adopting-session')
      this.host.setInputDisabled(true)
      await this.adoptSession(this.pendingSession)
      return
    }
    await this.runInitialTurn()
  }

  // Waits out the session upload, then drives the first clarification turn.
  private async adoptSession(pending: Promise<SubmissionSessionResponse | null>): Promise<void> {
    let session: SubmissionSessionResponse | null
    try {
      session = await pending
    } catch {
      session = null
    }
    if (this.gone()) return
    if (!session) {
      this.showSubmissionFailure()
      return
    }
    this.submissionSessionId = session.id
    this.submissionToken = session.token
    if (this.state === 'finalizing') return
    this.setState('conversing')
    this.host.setInputDisabled(false)
    if (!session.ai_clarify_available) {
      this.applyResult({ messages: [], done: true })
      return
    }
    await this.runInitialTurn()
  }

  // The feedback itself never reached the server, so there is no session to
  // converse with and nothing to finalize — only a full re-submission helps.
  private showSubmissionFailure(): void {
    this.setState('submission-failed')
    this.stopPolling()
    this.host.removeThinking()
    this.host.renderSubmissionFailureFooter()
  }

  async retrySubmission(): Promise<void> {
    if (!this.onRetrySubmission || this.isRequestInFlight() || this.gone()) return
    this.setState('adopting-session')
    this.host.showConversationControls()
    this.host.setInputDisabled(true)
    this.host.showThinking()
    await this.adoptSession(this.onRetrySubmission())
  }

  async sendAnswer(text: string): Promise<void> {
    if (!text || this.isRequestInFlight() || !this.submissionSessionId) return

    this.setState('answering')
    this.host.onAnswerTurnStarted(text)
    this.stopPolling()

    try {
      await this.runAnswerTurn(text)
    } catch {
      if (this.gone()) return
      this.setState('conversing')
      this.host.onAnswerTurnFailed(this.lastMessages, text)
    }
  }

  // Streams the assistant reply; falls back to POST + polling if the backend
  // doesn't support SSE (older server) or the stream errors mid-flight.
  //
  // A stream the server accepts but never terminates would leave the card
  // showing its thinking state forever. The deadline measures silence rather
  // than total time: a stream still delivering tokens is making progress and
  // is left alone, however long the answer turns out to be.
  private async runInitialTurn(): Promise<void> {
    const abort = new AbortController()
    this.streamAbort = abort
    let silenceTimer = setTimeout(() => abort.abort(), CLARIFY_SILENCE_TIMEOUT_MS)
    try {
      const result = await this.apiClient.streamClarification(
        this.submissionSessionId,
        this.submissionToken,
        (text) => {
          clearTimeout(silenceTimer)
          silenceTimer = setTimeout(() => abort.abort(), CLARIFY_SILENCE_TIMEOUT_MS)
          this.host.appendStreamDelta(text)
        },
        abort.signal,
      )
      if (this.abandoned()) return
      this.host.endStreamingBubble()
      if (!this.applyResult(result)) this.startPolling()
    } catch {
      if (this.abandoned()) return
      this.host.endStreamingBubble()
      await this.runInitialTurnViaPolling()
    } finally {
      clearTimeout(silenceTimer)
      if (this.streamAbort === abort) this.streamAbort = null
    }
  }

  private async runInitialTurnViaPolling(): Promise<void> {
    try {
      const res = await this.apiClient.startClarification(
        this.submissionSessionId,
        this.submissionToken,
      )
      if (this.abandoned()) return
      if (!this.applyResult(res)) this.startPolling()
    } catch {
      if (this.abandoned()) return
      this.handleFailure()
    }
  }

  private async runAnswerTurn(message: string): Promise<void> {
    const res = await this.apiClient.startClarification(
      this.submissionSessionId,
      this.submissionToken,
      message,
    )
    if (this.gone()) return
    if (!this.applyFinalSubmissionResult(res)) this.startPolling()
  }

  private startPolling(): void {
    this.stopPolling()
    this.pollDeadline = Date.now() + POLL_TIMEOUT_MS
    this.pollTimer = setInterval(() => this.poll(), POLL_INTERVAL_MS)
  }

  private stopPolling(): void {
    if (this.pollTimer !== null) {
      clearInterval(this.pollTimer)
      this.pollTimer = null
    }
  }

  private async poll(): Promise<void> {
    if (Date.now() > this.pollDeadline) {
      this.stopPolling()
      this.handleFailure()
      return
    }
    try {
      const res = await this.apiClient.getClarification(
        this.submissionSessionId,
        this.submissionToken,
      )
      if (this.gone()) return
      const settled = this.state === 'answering'
        ? this.applyFinalSubmissionResult(res)
        : this.applyResult(res)
      if (settled) this.stopPolling()
    } catch {
      if (this.gone()) return
      this.stopPolling()
      this.handleFailure()
    }
  }

  private handleDone(autoFinalize: boolean): void {
    if (this.hasSettled()) return
    this.setState('settled')
    this.stopPolling()
    this.host.removeThinking()
    if (autoFinalize) {
      void this.finalize()
      return
    }
    this.host.renderFinalizeButton()
  }

  private handleFailure(): void {
    if (this.hasSettled()) return
    this.setState('clarify-failed')
    this.stopPolling()
    this.host.removeThinking()
    this.host.renderClarifyFailureFooter()
  }

  async retryClarification(): Promise<void> {
    if (this.isRequestInFlight() || this.gone()) return

    this.setState('retrying')
    this.host.onRetryStarted(this.lastMessages)

    try {
      const snapshot = await this.apiClient.getClarification(this.submissionSessionId, this.submissionToken)
      if (this.gone()) return
      let result = snapshot
      // Each server status needs a different move. `processing` means a job is
      // already running for this session, so kicking off another turn would
      // duplicate it — fall through to polling instead. `awaiting_response` means
      // the assistant already asked its question and the server is waiting on the
      // reporter; applyResult hands the card back to them rather than polling for
      // a state only a human reply can change.
      if (snapshot.status === 'failed') {
        result = await this.apiClient.retryClarification(this.submissionSessionId, this.submissionToken)
      } else if (snapshot.status === 'idle') {
        result = await this.apiClient.startClarification(this.submissionSessionId, this.submissionToken)
      }
      if (this.gone()) return
      if (!this.applyResult(result)) {
        this.host.showConversationControls()
        this.startPolling()
      }
    } catch {
      if (this.gone()) return
      this.handleFailure()
    } finally {
      // Only unwind this method's own phase: applyResult may already have
      // settled the card (done, failed, or handed back to the reporter), and
      // an auto-finalize may be running — those states must stand.
      if (this.state === 'retrying') this.setState('conversing')
    }
  }

  // Returns true when the exchange has settled — the caller uses that to decide
  // whether it still needs to poll.
  //
  // The answer-turn result path, kept distinct from applyResult on purpose: it
  // deliberately never renders the final assistant reply. The reporter just
  // sent their answer and a completed exchange finalizes and destroys the card
  // on its own — repainting the transcript under the send button's spinner
  // would flash a message nobody has time to read, so the spinner holds until
  // finalize tears the card down.
  private applyFinalSubmissionResult(result: ClarifyResponse): boolean {
    if (result.status === 'failed') {
      this.handleFailure()
      return true
    }
    if (result.done) {
      this.handleDone(true)
      return true
    }
    return false
  }

  private applyResult(result: ClarifyStreamResult | ClarifyResponse): boolean {
    this.lastMessages = result.messages
    this.host.renderConversation(result.messages, result.done)
    const status = 'status' in result ? result.status : undefined
    const failed = 'status' in result ? result.status === 'failed' : result.failed === true
    if (failed) {
      this.handleFailure()
      return true
    }
    if (result.done) {
      // A completed AI exchange already has the reporter's answer and the
      // assistant's response, so submit it without asking for a second click.
      // Empty completed results mean AI clarification was unavailable, where
      // the reporter still needs an explicit way to send their feedback.
      this.handleDone(result.messages.some(message => message.role === 'assistant'))
      return true
    }
    if (status === 'awaiting_response') {
      // The ball is in the reporter's court: polling here would spin until the
      // deadline and then show a failure card for a perfectly healthy session.
      this.stopPolling()
      this.host.removeThinking()
      this.host.enableInput()
      return true
    }
    return false
  }

  async finalize(): Promise<void> {
    if (this.state === 'finalizing' || this.state === 'unrecoverable' || this.gone()) return

    this.setState('finalizing')
    this.host.onFinalizeStarted()
    try {
      await this.onFinalize()
    } catch (error) {
      if (this.gone()) return
      // Both failure footers below re-offer submission, which is the settled
      // family's job — the exchange itself is over either way.
      this.setState('settled')
      this.host.clearError()
      // A 409 means the server will never accept this session again (it expired
      // past its retention window, or was already finalized/abandoned). Offering
      // Retry there just loops the reporter through the same generic error, so say
      // what happened and what to do instead.
      if (isTerminalConflict(error)) {
        this.showUnrecoverable()
        return
      }
      this.host.renderFinalizeRetryFooter()
    }
  }

  private showUnrecoverable(): void {
    this.setState('unrecoverable')
    this.stopPolling()
    this.host.renderUnrecoverableFooter()
  }

  // Skip is "send without answering".
  skip(): void {
    // With no session on the server there is nothing to finalize: the failure
    // footer already offers Retry, so this path only reports the cancel.
    // Teardown ownership sits behind onCancel — the controller's exitAll — and
    // the card deliberately does not dismiss itself here.
    if (this.state === 'submission-failed') {
      this.onCancel?.()
      return
    }
    this.onSkip?.()
    // Start finalization before dismissal trips the destroyed guard, then take
    // the UI down while the request continues independently.
    void this.finalize()
    this.host.dismiss()
  }

  // The header X means "cancel — don't send" for as long as not sending is
  // still possible. Per state:
  // - submission-failed: nothing ever reached the server; cancelling is a
  //   plain dismissal.
  // - adopting-session / conversing / answering / retrying / clarify-failed /
  //   settled: the session may be uploaded but the feedback has not been sent
  //   (a finalize that succeeds destroys this card before it can be closed),
  //   so X routes to onCancel — the controller's exitAll — whose
  //   SubmissionLifecycle.abandon bumps the attempt and abandons the
  //   server-side session. If a finalize response was lost but did land, the
  //   server refuses to abandon a finalized session, so this can never un-send.
  // - unrecoverable: the server already treats the session as terminal; the
  //   abandon inside exitAll is refused there and only resets local state.
  // - finalizing: the send is on the wire. Abandoning now would race the
  //   finalize (and the attempt bump would drop its success), so X must not
  //   cancel — it dismisses the card and lets the finalize continue in the
  //   background, exactly like the Skip path's dismissal minus a second
  //   finalize call.
  close(): void {
    if (this.state === 'finalizing') {
      this.onSkip?.()
      this.host.dismiss()
      return
    }
    this.onCancel?.()
    this.host.dismiss()
  }

  /** The card is being destroyed: silence every continuation and hang up. */
  dispose(): void {
    this.destroyed = true
    this.streamAbort?.abort()
    this.streamAbort = null
    this.stopPolling()
  }
}
